### ISSUE TITLE
更新されたバージョンのF-Droidへのアップロード

### ISSUE THREAD

**Issue by TranslucentFoxHuman** [gorry/nicoWnnG#1]
初めまして。nicoWnnGをいつも愛用させていただいております。

私は以前F-DroidよりnicoWnnGをダウンロードし使用しておりましたが、少し前にGorry様のサイトとPlayストアにて更新されたバージョンがあることに気付きました。
F-Droidでは署名が異なるため、署名偽装の出来ない環境ではそのままでは更新が出来ません。

F-Droidへ更新されたバージョンをアップロードするご予定はありますでしょうか?

**Comment by gorry** [comment]
f-droidにアップロードされたバイナリは、当方がビルド・アップロードしたものではありません。
nicoWnnGはソースが公開されており、これを他人がビルド・アップロードすることを特に禁止しておりませんので、それらの行為をなされた方に要請されてはいかがでしょうか。
なお、「当方がビルド・アップロードしたもの」よりも「他人様がビルド・アップロードされたもの」を志向される理由がもしおありなら、ご教示いただければ幸いです。

**Comment by TranslucentFoxHuman** [comment]
お忙しい中対応頂きありがとうございます。

F-Droidにアップロードされたものは非公式だったのですね。
F-Droidのものはアップロード者の記載が無く、勘違いをしておりました。
公式バイナリへ移行させていただきます。

**Comment by onitake** [comment]
nicoWnnGの開発を再会させてありがとうございました。
ただ今F-DroidDataのリポジトリーで更新PRを開けました：https://gitlab.com/fdroid/fdroiddata/-/merge_requests/15058
